const cardText =document.getElementById("cardText");
const cards = new Map();
cards.set(1, "Remove specifics and convert to ambiguities");
cards.set(2, "Think of the radio");
cards.set(3, "Don't be frightened of clichés");
cards.set(4, "Allow an easement" + "<br>" + "(an easement is the abandonment of a stricture)");
cards.set(5, "What is the reality of the situation?");
cards.set(6, "Simple subtraction");
cards.set(7, "Are there sections? Consider transitions");
cards.set(8, "Turn it upside down");
cards.set(9, "Go slowly all the way round the outside");
cards.set(10, "A line has two sides");
cards.set(11, "Infinitesimal gradations");
cards.set(12, "Make an exhaustive list of everything you might do and do the last thing on the list");
cards.set(13, "Change instrument roles");
cards.set(14, "Into the impossible");
cards.set(15, "Accretion");
cards.set(16, "Ask people to work against their better judgment");
cards.set(17, "Disconnect from desire");
cards.set(18, "Take away the elements in order of apparent non-importance");
cards.set(19, "Emphasize repetitions");
cards.set(20, "Ask people to work against their better judgment");
cards.set(21, "Don't be afraid of things because they're easy to do");
cards.set(22, "Don't be frightened to display your talents");
cards.set(23, "Breathe more deeply");
cards.set(24, "Honor thy error as a hidden intention");
cards.set(25, "Only one element of each kind");
cards.set(26, "Use unqualified people");
cards.set(27, "How would you have done it?");
cards.set(28, "Emphasize differences");
cards.set(29, "Do nothing for as long as possible");
cards.set(30, "Bridges - build - burn");
cards.set(31, "Water");
cards.set(32, "You don't have to be ashamed of using your own ideas");
cards.set(33, "Tidy up");
cards.set(34, "Do the words need changing?");
cards.set(35, "Ask your body");
cards.set(36, "Make a sudden, destructive unpredictable action; incorporate");
cards.set(37, "Consult other sources");
cards.set(38, "Use an unacceptable color");
cards.set(39, "Humanize something free of error");
cards.set(40, "Use filters Balance the consistency principle with the inconsistency principle");
cards.set(41, "Fill every beat with something");
cards.set(42, "Discard an axiom");
cards.set(43, "What wouldn't you do?");
cards.set(44, "Decorate, decorate");
cards.set(45, "Do nothing for as long as possible");
cards.set(46, "Listen to the quiet voice");
cards.set(47, "Is it finished?");
cards.set(48, "Put in earplugs");
cards.set(49, "Give the game away Reverse");
cards.set(50, "Abandon normal instruments");
cards.set(51, "Use fewer notes");
cards.set(52, "Repetition is a form of change");
cards.set(53, "Give way to your worst impulse");
cards.set(54, "Trust in the you of now");
cards.set(55, "What would your closest friend do?");
cards.set(56, "Distorting time");
cards.set(57, "Make a blank valuable by putting it in an exquisite frame");
cards.set(58, "The inconsistency principle");
cards.set(59, "Ghost echoes");
cards.set(60, "You can only make one dot at a time");
cards.set(61, "Just carry on");
cards.set(62, "(Organic) machinery");
cards.set(63, "Don't break the silence");
cards.set(64, "Discover the recipes you are using and abandon them");
cards.set(65, "Cascades");
cards.set(66, "Courage!");
cards.set(67, "What mistakes did you make last time? You are an engineer");
cards.set(68, "Consider different fading systems");
cards.set(69, "Mute and continue");
cards.set(70, "It is quite possible (after all)");
cards.set(71, "Don't stress one thing more than another");
cards.set(72, "Remove ambiguities and convert to specifics");
cards.set(73, "Look at the order in which you do things");
cards.set(74, "Go outside. Shut the door.");
cards.set(75, "Do we need holes?");
cards.set(76, "Cluster analysis Work at a different speed");
cards.set(77, "Do something boring");
cards.set(78, "Define an area as ‘safe’ and use it as an anchor");
cards.set(79, "Overtly resist change");
cards.set(80, "Accept advice");
cards.set(81, "Look closely at the most embarrassing details and amplify them");
cards.set(82, "Mechanicalize something idiosyncratic");
cards.set(83, "Emphasize the flaws");
cards.set(84, "Remember those quiet evenings");
cards.set(85, "Take a break The tape is now the music");
cards.set(86, "Short circuit");
cards.set(87, "Use an old idea");
cards.set(88, "Destroy - nothing - the most important thing");
cards.set(89, "Change nothing and continue with immaculate consistency");
cards.set(90, "Imagine the music as a moving chain or caterpillar");
cards.set(91, "Intentions - credibility of - nobility of - humility of");
cards.set(92, "Imagine the music as a set of disconnected events");
cards.set(93, "Imagine the piece as a set of disconnected events");
cards.set(94, "What are you really thinking about just now?");
cards.set(95, "Incorporate.");
cards.set(96, "Children's voices - speaking - singing");
cards.set(97, "Assemble some of the instruments in a group and treat the group");
cards.set(98, "Shut the door and listen from outside");
cards.set(99, "Is the tuning appropriate?");
cards.set(100, "Look at a very small object, look at its centre");
cards.set(101, "Feedback recordings into an acoustic situation");
cards.set(102, "Towards the insignificant");
cards.set(103, "Simply a matter of work");
cards.set(104, "Not building a wall but making a brick");
cards.set(105, "Revaluation (a warm feeling) Disciplined self-indulgence");
cards.set(106, "The most important thing is the thing most easily forgotten");
cards.set(107, "Idiot glee");
cards.set(108, "Be extravagant");
cards.set(109, "State the problem in words as clearly as possible");
cards.set(110, "Always first steps");
cards.set(111, "Question the heroic approach");
cards.set(112, "Always give yourself credit for having more than personality");
cards.set(113, "Faced with a choice, do both");
cards.set(114, "Tape your mouth");
cards.set(115, "Twist the spine");
cards.set(116, "Get your neck massaged");
cards.set(117, "Do the washing up");
cards.set(118, "Convert a melodic element into a rhythmic element");
cards.set(119, "Spectrum analysis");
cards.set(120, "Lowest common denominator check - single beat - single note - single riff");
cards.set(121, "Listen in total darkness, or in a very large room, very quietly");
cards.set(122, "Would anybody want it?");
cards.set(123, "Retrace your steps");
cards.set(124, "Go to an extreme, move back to a more comfortable place");
cards.set(125, "Once the search is in progress, something will be found");
cards.set(126, "Only a part, not the whole");
cards.set(127, "From nothing to more than nothing");
cards.set(128, "Be less critical more often");




function showRandomCard(cards){

    const keys = Array.from(cards.keys()); 
    const randomKey = keys[Math.floor(Math.random() * cards.size)]; 
    cardText.innerHTML = cards.get(randomKey);  

}

